server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterUnicoding=UTF8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

    type: com.alibaba.druid.pool.DruidDataSource

    druid:
      initialSize: 5
      max-active: 10
      min-idle: 5
      max-wait: 3000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      #测试连接是否可用的SQL语句，SELECT 1是MySQL的默认值
      validationQuery: SELECT 1
      # 应用向连接池获取连接的时候测试连接的有效性
      testWhileIdle: true
      testOnBorrow: false
      # 设置从连接池归还连接时是否检查连接有效性，true检查，false不检查
      testOnReturn: false
      # 开启PreparedStatements Cache(提升写入、查询效率)，MySQL5.7以上建议true
      poolPreparedStatements: true
      # 打开Druid的监控统计功能
      # stat监控统计  log4j日志监控  wall防御sql注入
      filters: stat,wall,log4j
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

  thymeleaf:
    cache: false
    prefix: classpath:/templates/water/
    suffix: .html

  resources:
    static-locations: classpath:/static,classpath:/public,classpath:/resources,classpath:/META-INF/resource,file:${location}


location: E:\dpan\bugbuff\Change_Picture\upload

mybatis:
  type-aliases-package: com.whut.springboot.entities
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mappers/*Mapper.xml
# 分页配置
pagehelper:
  # 指定分页插件使用哪种方言
  helper-dialect: mysql
  # 分页合理化参数，默认为false，当该值为true，pageNum<=0默认查询第一页，
  # pageNum>pages时会查询最后一页，false时直接根据参数进行查询
  reasonable: true
  # 支持通过Mapper接口参数来传递分页参数
  support-methods-arguments: true
  params: count=countsql