server:
  port: 8089

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterUnicoding=UTF8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    druid:
      max-active: 10
      min-idle: 5
      max-wait: 3000

  thymeleaf:
    cache: false
    prefix: classpath:/templates/water
    suffix: .html

mybatis:
  type-aliases-package: com.whut.springboot.entities
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mappers/*Mapper.xml